title: custom-git
description: An open source, general-purpose, highly efficient command line git tool.
show_downloads: false
google_analytics: G-ZTWKKERPZW
theme: jekyll-theme-leap-day
github:
  repository_url: https://github.com/custom-git/custom-git-bash
  is_project_page: true
  owner_url: https://github.com/bhavidhingra
  owner_name: bhavidhingra
