title: custom-git
description: An open source, general-purpose, command line git tool for high productivity.
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
plugins: jekyll-redirect-from