#!/bin/bash

#shellcheck disable=SC2184      # Quote arguments to unset so they're not glob expanded.
#shellcheck disable=SC2088      # Tilde does not expand in quotes. Use $HOME.
#shellcheck disable=SC2053      # Quote the right-hand side of != in [[ ]] to prevent glob matching.
#shellcheck disable=SC2091      # Remove surrounding $() to avoid executing output (or use eval if intentional).
#shellcheck disable=SC2086      # Double quote to prevent globbing and word splitting.

##################
# util functions #
##################

SUCCESS=0
FAILURE=1

MOVE_UP=$(tput cuu 1)
CLEAR_LINE=$(tput el 1)

function mucl() {
    echo "${MOVE_UP}${CLEAR_LINE}${MOVE_UP}"
}

currDir="$(pwd)"

function finish {
    cd "${currDir}" || {
        banner_color_err 0 "couldn't enter directory: ${currDir}" 2
        exit ${FAILURE}
    }
}
trap finish EXIT

function apply_tput() {

    case "${1}" in
        black) tput setaf 0
        ;;
        red) tput setaf 1
        ;;
        green) tput setaf 2
        ;;
        yellow) tput setaf 3
        ;;
        blue) tput setaf 4
        ;;
        magenta) tput setaf 5
        ;;
        cyan) tput setaf 6
        ;;
        white) tput setaf 7
        ;;
        reset) tput sgr0
        ;;
        *) tput "${1}"
        ;;
    esac
}

# Usage: insert_new_lines 3
function insert_new_lines() {
    for (( i = 0; i < ${1}; i++)); do
        echo
    done
}

# Usage: banner_color 1 "red" "*" "my title" 2
function banner_color() {
    insert_new_lines ${1}

    apply_tput "${2}"
    apply_tput bold

    local msg="${3} ${4} ${3}"
    local edge
    edge=${msg//?/$3}
    echo "${edge}"
    echo "${msg}"
    printf "%s" "${edge}"

    apply_tput reset

    insert_new_lines ${5}
}

# Usage: banner_color_err 1 "error msg" 2
function banner_color_err() {
    banner_color ${1} "red" "~" "[ERROR] ${2}" ${3}
}

# Usage: print_as 3 "blue" "msg" 1
function print_as() {
    insert_new_lines ${1}; shift

	while [[ $# -gt 2 ]]; do
		apply_tput "${1}"; shift
	done
	local msg="${1}"; shift
	printf "%s" "${msg}"
	apply_tput reset

    insert_new_lines ${1};
}

# Usage: print_info 3 "msg" 2
function print_info() {
	print_as ${1} "blue" "[INFO] ${2}" ${3}
}

# Usage: print_err 3 "msg" 2
function print_err() {
	print_as ${1} "red" "[ERROR] ${2}" ${3}
}

function is_command_installed() {

    if command -v "${1}" &>/dev/null; then
        echo true
    else
        echo false
    fi
}

function append_line() {
    set -e

    local line="${1}" file="${2}" pat="${3:-}" lno=""

    if [ -f "$file" ]; then
        if [ $# -lt 4 ]; then
            lno=$(grep -nF "$line" "$file" | sed 's/:.*//' | tr '\n' ' ')
        else
            lno=$(grep -nF "$pat" "$file" | sed 's/:.*//' | tr '\n' ' ')
        fi
    fi
    if [ -z "$lno" ]; then
        [ -f "$file" ] && echo >> "$file"
        echo "$line" >> "$file"
    fi
    set +e
}

function remove_file() {
    local file="${1}"
    [ -f "${file}" ] && {
        print_info "Remove ${file}"
        rm -f "${file}"
    }
}


function remove_line() {
    src=$(readlink "$1")
    if [ $? -eq 0 ]; then
        echo "Remove from $1 ($src):"
    else
        src=$1
        echo "Remove from $1:"
    fi

    shift
    line_no=1
    match=0
    while [ -n "$1" ]; do
        line=$(sed -n "$line_no,\$p" "$src" | \grep -m1 -nF "$1")
        if [ $? -ne 0 ]; then
            shift
            line_no=1
            continue
        fi
        line_no=$(( $(sed 's/:.*//' <<< "$line") + line_no - 1 ))
        content=$(sed 's/^[0-9]*://' <<< "$line")
        match=1
        echo    "  - Line #$line_no: $content"
        [ "$content" = "$1" ] || ask "    - Remove?"
        if [ $? -eq 0 ]; then
            awk -v n=$line_no 'NR == n {next} {print}' "$src" > "$src.bak" &&
            mv "$src.bak" "$src" || break
            echo  "      - Removed"
        else
            echo  "      - Skipped"
            line_no=$(( line_no + 1 ))
        fi
    done
    [ $match -eq 0 ] && echo "  - Nothing found"
    echo
}

# Usage: assert_equal A B msg
function assert_equal() {

    local A="${1}" B="${2}" msg="${3}"
    [[ "${A}" != "${B}" ]] && {
        mucl
        banner_color_err 0 "${msg}" 2
        exit ${FAILURE}
    }
}

# Usage: assert_success msg
function assert_success() {

    local status="$?" msg="${1}"
    assert_equal "${status}" ${SUCCESS} "${msg}"
}

function get_current_branch() {
    git rev-parse --abbrev-ref HEAD
}

function install_clipboard() {

    clipboard_installation_status=$SUCCESS

    if ! $(is_command_installed "npm"); then
        clipboard_installation_status=$FAILURE
        banner_color_err 1 "npm not installed." 2
        return
    fi
    print_info 0 "Installing clipboard-cli ..." 1
    sudo npm install -g clipboard-cli &> /dev/null

    if (( $? != SUCCESS )); then
        clipboard_installation_status=$FAILURE
        mucl
        mucl
        banner_color_err 0 "clipboard-cli installation failed." 2
        return
    fi

    mucl
    mucl
    banner_color 0 "magenta" "*" "clipboard-cli installed." 2
}

function install_fzf() {

    print_info 0 "Installing fzf ..." 1

    fzf_installation_status=${SUCCESS}
    git clone --depth 1 https://github.com/junegunn/fzf.git "${FZF_HOME}" &> /dev/null
    cd "${FZF_HOME}" || {
        fzf_installation_status=$FAILURE
        mucl
        banner_color_err 0 "couldn't enter directory: ${FZF_HOME}" 2
        return
    }
    ./install --all &> /dev/null

    if (( $? != SUCCESS )); then
        fzf_installation_status=${FAILURE}
        mucl
        banner_color_err 0 "fzf installation failed." 2
        return
    fi

    mucl
    banner_color 0 "magenta" "*" "fzf installed." 2
}


#####################
# Update custom-git #
#####################

insert_new_lines 1

shells=("bash" "zsh")
numShells=${#shells[@]}

for ((i = 0 ; i < numShells ; i++)); do
    shell="${shells[$i]}"
    if ! $(is_command_installed "${shell}"); then
        unset shells[$i]
    fi
done

if [[ ${#shells[@]} -eq 0 ]]; then
    banner_color_err 0 "custom-git is only supported for bash and zsh shells. Stopping updation." 2
    print_info 0 "Visit " 0
    print_as 0 "magenta" "bold" "https://custom-git.io" 0
    print_as 0 "blue" " for more information." 2
    exit ${FAILURE}
fi

prefix='~/.custom-git'

CUSTOM_GIT_HOME="${HOME}"/.custom-git
FZF_HOME="${HOME}"/.fzf
CUSTOM_GIT_BASH_REPO_URL="https://github.com/custom-git/custom-git-bash"

if [[ ! -d "${CUSTOM_GIT_HOME}" ]]; then
    banner_color_err 0 "custom-git is not installed on your system." 2
    print_info 0 "Visit " 0
    print_as 0 "magenta" "bold" "https://custom-git.io" 0
    print_as 0 "blue" " for easy installation." 2
    exit ${FAILURE}
fi

if ! $(is_command_installed "clipboard"); then

    install_clipboard
    if [[ $clipboard_installation_status -eq $FAILURE ]]; then
        print_info 0 "Please install clipboard-cli from " 0
        print_as 0 "magenta" "bold" "\"https://github.com/sindresorhus/clipboard-cli\"" 1
        print_info 0 "Otherwise, some custom-git commands may not work correctly." 2
    fi
fi

if ! $(is_command_installed "fzf"); then

    install_fzf
    if [[ $fzf_installation_status -eq $FAILURE ]]; then
        print_info 0 "Please install fzf from " 0
        print_as 0 "magenta" "bold" "https://github.com/junegunn/fzf#installation" 1
        print_as 0 "blue" "and try again..." 2
        exit ${FAILURE}
    fi
fi

cd "${CUSTOM_GIT_HOME}" || {
    banner_color_err 0 "couldn't enter directory: ${CUSTOM_GIT_HOME}" 2
    exit ${FAILURE}
}

latestReleaseVersion="release-1.0"
print_info 0 "Updating custom-git to ${latestReleaseVersion}..." 1

currVersion="$(get_current_branch)"
case "${currVersion}" in
    release-0.1|main|HEAD)
        for shell in "${shells[@]}"; do
            initFile="${CUSTOM_GIT_HOME}.${shell}"
            remove_file "${initFile}"
            remove_line ~/.${shell}rc \
                "[ -f ${prefix}.${shell} ] && source ${prefix}.${shell}" \
                "source ${prefix}.${shell}"
        done
    ;;
    *)
    ;;
esac

if [[ "${currVersion}" != "HEAD" ]]; then
    git pull --ff-only &> /dev/null
    assert_success "Fast-Forward failed. Please check your network."
else
    clone_depth=$(git rev-list --count --all)
    if [[ ${clone_depth} -eq 1 ]]; then
        git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
        git fetch --unshallow &> /dev/null
    else
        git fetch &> /dev/null
    fi
    assert_success "Fetching custom-git failed. Please check your network."
fi

git checkout "${latestReleaseVersion}" &> /dev/null
assert_success "Switching to new version failed. Please check your network."

git submodule update --init &> /dev/null
assert_success "Submodule update failed. Please check your network."

newVersion="$(get_current_branch)"
assert_equal "${newVersion}" "${latestReleaseVersion}" \
    "Couldn't update custom-git to ${latestReleaseVersion}. Unknown error."

for shell in "${shells[@]}"; do
    [ $shell = zsh ] && dest=${ZDOTDIR:-~}/.zshrc || dest=~/.bashrc
    append_line "[ -f ${prefix}/init.${shell} ] && source ${prefix}/init.${shell}" \
        "$dest" "source ${prefix}/init.${shell}"
done

mucl
banner_color 0 "magenta" "*" "custom-git updated to ${latestReleaseVersion}." 2

print_info 0 "Restart your shell or reload config file." 1
for shell in "${shells[@]}"; do
    case "${shell}" in
        bash)
            printf "   source ~/.bashrc  # bash"
            archi=$(uname -sm)
            [[ "$archi" =~ Darwin ]] && printf "  (~/.bashrc should be sourced from ~/.bash_profile)"
            echo
            ;;
        zsh)
            echo "   source ${ZDOTDIR:-~}/.zshrc   # zsh"
            ;;
        *)
            printf "\n   %s shell is not supported.\n" "${shell}"
            ;;
    esac
done

print_info 1 "For more details, visit: " 0
print_as 0 "magenta" "bold" "${CUSTOM_GIT_BASH_REPO_URL}" 2